version: "3"
volumes:
  logs:
services:
  # MongoDB container
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    env_file:
      - .env
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./data/mongo-db-volume:/data/db
    restart: always
    networks:
      - node-webapp-network
  # NodeJS container
  backend:
    depends_on:
      - mongodb
    build: .
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./logs:/app/logs
    links:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge
