on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --ignore-scripts
      - run: yarn build
      - run: yarn lint
      - run: git diff --exit-code